apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: timoweb
  namespace: argocd
spec:
  generators:
  - list:
      cluster: dev
      url: https://3A8E48E723BA33BFC0D3C6CA49CBD0BD.gr7.ap-southeast-1.eks.amazonaws.com
      name: dev-timoweb
  template:
    metadata:
      name: {{name}}
    spec:
      project: '{{cluster}}-cluster-1'
      destination:
        namespace: timoweb
        server: '{{url}}'
      sources:
        - chart: wordpress
          repoURL: "https://github.com/LeoPhat/wp-maria-nginx/wordpress/"
          targetRevision: 6.3.2
        - chart: mariadb-operator
          repoURL: "https://mariadb-operator.github.io/mariadb-operator"
          targetRevision: 0.21.0
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
