apiVersion: mariadb.mmontes.io/v1alpha1
kind: User
metadata:
  name: user-wordpress
spec:
  mariaDbRef:
    name: mariadb
  passwordSecretKeyRef:
    name: wordpress-password
    key: password
  maxUserConnections: 20