apiVersion: mariadb.mmontes.io/v1alpha1
kind: User
metadata:
  name: wordpress
spec:
  mariaDbRef:
    name: mariadb
  passwordSecretKeyRef:
    name: wordpress
    key: wordpress-password
  maxUserConnections: 20